config/routes.rb
require 'api_constraints'

GymTracker::Application.routes.draw do

  namespace :api, defaults: {format: :json} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :exercises, only: [:index, :show, :create, :update, :destroy]
      resources :workout_sets, path: 'sets', only: [:index, :show, :create, :update, :destroy]
    end
  end

  root :to => "home#index"
  get '/dashboard' => 'templates#index'
  get '/exercises/:id' => 'templates#index'
  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

  post 'signin', to: redirect('/auth/facebook'), as: 'signin'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  

end

app/models/exercise.rb
class Exercise
  include Mongoid::Document
  field :name, type: String

  has_many :workout_sets

  belongs_to :user

  validates_presence_of       :name
  validates_length_of         :name, maximum: 50
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, :type => String
  field :uid, :type => String
  field :provider, :type => String

  has_many :exercises

  def self.from_omniauth(auth)
    user = where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    return user
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["nickname"]
    end
  end
end

app/models/workout_set.rb
class WorkoutSet
  include Mongoid::Document

  field :weight, type: Float
  field :reps, type: Integer
  field :date, type: Date

  belongs_to :exercise

  validates_presence_of       :reps
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  before_filter :authenticate

  private

  def permission_denied
    render json: {error: 'unauthorized'}, status: :unauthorized
  end
end

app/controllers/api/v1/exercises_controller.rb
class Api::V1::ExercisesController < Api::V1::BaseController

  before_action :check_owner, only: [:show, :update, :destroy]

  def index
    render json: exercises, serializer: ExercisesSerializer
  end

  def show
    render json: exercise, status: 200, serializer: ExerciseSerializer
  end

  def create
    ex = Exercise.create!(safe_params.merge user_id: current_user.id)
    render json: ex, status: 201, serializer: ExerciseSerializer
  end

  def update
    exercise.update_attributes(safe_params)
    render nothing: true, status: 204
  end

  def destroy
    workout_sets = WorkoutSet.where(exercise_id: exercise.id)
    workout_sets.each do |workout_set|
      workout_set.destroy
    end
    exercise.destroy
    render nothing: true, status: 204
  end

  private
  def exercises
    @exercises ||= Exercise.where(user_id: current_user.id)
  end

  def exercise
    @exercise ||= Exercise.where(_id: params[:id]).first
  end

  def safe_params
    params.require(:exercise).permit(:id, :name)
  end

  def check_owner
    permission_denied if current_user != exercise.user
  end
end

app/controllers/api/v1/workout_sets_controller.rb
class Api::V1::WorkoutSetsController < Api::V1::BaseController
  #before_action :check_owner

  def index
    render json: workout_sets, serializer: WorkoutSetsSerializer
  end

  def show
    render json: workout_set, status: 200, serializer: WorkoutSetSerializer
  end

  def create
    workout_set = WorkoutSet.create!(safe_params)
    if workout_set.date.nil?
      workout_set.date = Time.now
    end
    workout_set.save
    render json: workout_set, status: 201, serializer: WorkoutSetSerializer
  end

  def update
    workout_set.update_attributes(safe_params)
    render nothing: true, status: 204
  end

  def destroy
    workout_set.destroy
    render nothing: true, status: 204
  end

  private
  def workout_sets
    @workout_sets ||= WorkoutSet.all
  end

  def workout_set
    @workout_set ||= WorkoutSet.where(_id: params[:id]).first
  end

  def safe_params
    params.require(:workout_set).permit(:id, :exercise_id, :weight, :reps, :date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  def permission_denied
    render file: "public/401.html", layout: false, status: :unauthorized
  end

  def current_user
    return nil if session[:user_id].nil?
    @current_user ||= User.where(_id: session[:user_id]).first
    if @current_user.nil?
      return nil
    end
    return @current_user
  end
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless current_user.nil?
      redirect_to dashboard_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  #before_filter :authenticate_user!

  def index
    
  end

  def template
    render :template => 'templates/' + params[:path], :layout => nil
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  include ApplicationHelper


  def authenticate
    permission_denied if current_user.nil?
  end
  
end

app/views/home/index.html.slim
h3 The best tool to track your gym exercises

.panel.panel-default
  .panel-heading
    h3.panel-title Features

  .panel-body
    ul
      li Add your own exercises
      li Add your own workouts
      li Login with Facebook

.panel.panel-default
  .panel-heading
    h3.panel-title Why?

  .panel-body
    ul
      li Get healthier 
      li Get more power
      li Improve every day

a.hidden-xs(href="https://github.com/danpersa/gym-tracker" id="github-ribbon")
  img(alt="Fork me on GitHub" id="github-ribbon" src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png" style="position: absolute; top: 0; left: 0; border: 0; z-index: 10000;")

app/views/layouts/_flash.html.slim
- if notice.present?
  div.alert.alert-success.alert-dismissable
    button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      ' &times
    =notice
- if alert.present?
  div.alert.alert-dismissable.alert-danger
    button(type="button" class="close" data-dismiss="alert" aria-hidden="true")
      ' &times
    = alert

app/views/layouts/_navigation.html.slim
.navbar.navbar-fixed-top.navbar-inverse role='navigation'
  .container
    .navbar-header
      button.navbar-toggle type='button' data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only 'Toggle navigation'
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Gym Tracker", root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href='#' Home
        li
          a href='#about' About
        li
          a href='#contact' Contact
      ul.nav.navbar-nav.navbar-right
        - unless current_user.nil?
          li
            = link_to "Welcome #{current_user.name}", "#"
          li
            = link_to "Log out", signout_path, method: :delete
        - else
          li 
            = link_to "Sign In", signin_path, method: :post

app/views/layouts/application.html.slim
doctype html
html
  head
    = tag 'meta', 'charset' => 'utf-8'
    = tag 'meta', 'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1.0'
    title Gym Tracker
    = stylesheet_link_tag    "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body(ng-app="gymTrackerApp")
    = render "layouts/navigation"
    .container    
      = render "layouts/flash"
      = yield

app/views/templates/dashboard.html.slim
.ng-cloak(ng-init="init()")

  div.panel.panel-default.dashboard-list
    div.panel-heading 
      h4 Your exercises
    ul.list-group(ng-show="exercises == 0")
      li.list-group-item
        ' You haven't created any exercises yet.      
    ul.list-group
      li.list-group-item(ng-repeat="exercise in exercises")
        button.btn.btn-danger.btn-xs.pull-right(type="button" ng-click="deleteExercise(exercise, $index)")
          span.glyphicon.glyphicon-ban-circle        
        a(href="/exercises/{{exercise.id}}") 
          ' {{exercise.name}}

  form#new_list(ng-submit="createExercise(exerciseName)")
    .input-group
      input#exerciseDescription.form-control.input-lg(type="text" autofocus="autofocus" placeholder="Exercise name" maxlength="255" ng-model="exerciseName" data-non-blank)
      span.input-group-btn
        button.btn.btn-primary.btn-lg(type="submit") create exercise

  

app/views/templates/index.html.slim
.ng-cloak
  
  div(ng-view)  
  
    
    

app/views/templates/workout_sets.html.slim
.ng-cloak(ng-init="init()")
  div.panel.panel-info.exercises
    div.panel-heading     
      editablespan(model="list.name" on-ready="exerciseNameEdited(list.name)" input-class="form-control" span-class="list-name")

    form#new_workout(ng-submit="addWorkoutSet()")
      .input-group
        input#workoutWeight.form-control.input-lg(type="number" autofocus="autofocus" placeholder="Weight" maxlength="10" ng-model="workoutSetWeight" data-non-blank)
        input#workoutReps.form-control.input-lg(type="number" placeholder="Reps" maxlength="10" ng-model="workoutSetReps" data-non-blank)
        span.input-group-btn
          button.btn.btn-primary.btn-lg(type="submit") add
    ul.list-group(ng-model="list.workout_sets")
      li.list-group-item(ng-repeat="workoutSet in list.workout_sets")
        //.workout-completed
        //  input(type="checkbox" ng-model="workout.completed" ng-change="toggleWorkoutSet(workout)")
        .div.row
          .div.col-md-5.col-xs-4
            editablespan(model="workoutSet.weight" on-ready="workoutSetEdited(workoutSet)" input-class="form-control")
          .div.col-md-5.col-xs-4
            editablespan(model="workoutSet.reps" on-ready="workoutSetEdited(workoutSet)" input-class="form-control" input-type="number")
          .div.col-md-2.col-xs-4
            .workout-buttons.pull-right
              button.btn.btn-danger.btn-xs.pull-right(type="button" ng-click="deleteWorkoutSet(workoutSet)")
                span.glyphicon.glyphicon-ban-circle
              calendar(model="workoutSet.date" on-change="datePicked(workoutSet)")
                button.btn.btn-info.btn-xs.pull-right(type="button")
                  span.glyphicon.glyphicon-time
        .workout-date(ng-show="workoutSet.date")
          small
            ' Date: {{workoutSet.date}}